name: HyperCTui
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - qt=5.12.9
  - pandas
  - pillow
  - scikit-image
  - inflect
  - qtpy=1.6.0
  - pyqt=5.*
  - astropy
  - numpy
  - dxchange
  - h5py=3.3.0
  - tomopy
  - pyqtgraph
  - tqdm
  - dxchange
  - pip:
      - NeuNorm
      - inflect
      - neutronbraggedge
