# load information from pyproject.toml
{% set pyproject = load_file_data('pyproject.toml') %}
{% set project = pyproject.get('project', {}) %}
{% set license = project.get('license').get('text') %}
{% set description = project.get('description') %}
{% set project_url = pyproject.get('project', {}).get('urls') %}
{% set url = project_url.get('homepage') %}
# this will get the version set by environment variable
{% set version = environ.get('VERSION') %}
{% set version_number = version.split('+')[0] %}
# change the build number by hand if you want to rebuild the package
{% set build_number = 0 %}

package:
  name: hyperctui
  version: {{ version_number }}

source:
  path: ..

build:
  noarch: python
  number: {{ build_number }}
  string: py{{py}}
  script:
    - {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv
    - {{ PYTHON }} -m pip install git+https://github.com/ornlneutronimaging/BraggEdge.git --no-deps --no-build-isolation -vvv
    - {{ PYTHON }} -m pip install git+https://github.com/ornlneutronimaging/NeuNorm.git --no-deps --no-build-isolation -vvv


requirements:

  host:
    - python
    - pip
    - versioningit

  build:
    - pip
    - setuptools
    - versioningit

  run:
    - python {{ python }}
    - pip
    - setuptools
    - tomopy
    - astropy
    - dxchange
    - tqdm
    - inflect
    - qt
    - qtpy
    - pyqt
    - pyqtgraph
    - pandas
    - pillow
    - scikit-image
    - loguru


about:
  home: {{ url }}
  license: {{ license }}
  license_family: MIT
  license_file: ../LICENSE
  summary: {{ description }}

extra:
  recipe-maintainers:
    - JeanBilheux
    - kedokudo
